---
- name: install ansible docker bindings (optional)
  apt:
    name:
      - python-docker
      - python3-docker

- name: remove stale docker container (optional, so ok to fail)
  docker_container:
    name: mtproxy
    state: absent
  ignore_errors: yes
  no_log: true
...
