---
- name: install ansible docker bindings (optional)
  apt:
    name: "{{ lin_use_python2 |ternary('python-docker,python3-docker', 'python3-docker') }}"

- name: remove stale docker container (optional, so ok to fail)
  docker_container:
    name: mtproxy
    state: absent
  ignore_errors: true
  no_log: "{{ hide_secrets |bool }}"
...
