---
- name: install ansible docker bindings (optional)
  apt:
    name: "{{ ansible_python_version.startswith('3') | ternary('python3','python') }}-docker"

- name: remove stale docker container (optional, so ok to fail)
  docker_container:
    name: mtproxy
    state: absent
  ignore_errors: yes
  no_log: true
...
