---
- name: remove stale docker container
  include_tasks: rmdocker.yml
  when: mtproxy_rmdocker |bool
  tags: mtproxy_rmdocker

- name: create group for proxy processes
  group:
    name: proxy
    gid: 13


- name: detect latest mtg release
  uri:
    url: https://github.com/9seconds/mtg/releases/latest
    method: HEAD
    creates: "{{ mtproxy_reinstall | bool | ternary(omit, mtproxy_bin_file) }}"
  register: latest_mtg_release
  when: mtproxy_release == 'latest'
  tags: mtproxy_install

- name: extract mtg version from github page
  set_fact:
    mtproxy_release: "{{ latest_mtg_release.url | basename }}"
  when: latest_mtg_release.url is defined
  tags: mtproxy_install

- name: print mtg version
  debug:
    msg: "latest mtg release: {{ mtproxy_release }}"
  run_once: true
  when: latest_mtg_release.url is defined
  tags: mtproxy_install

- name: download mtproxy
  get_url:
    url: https://github.com/9seconds/mtg/releases/download/{{ mtproxy_release }}/mtg-linux-amd64
    dest: "{{ mtproxy_bin_file }}"
    mode: 0755
    force: "{{ mtproxy_reinstall | bool }}"
  when: mtproxy_release != 'latest'
  tags: mtproxy_install


- name: configure mtproxy service
  template:
    src: mtproxy.defaults
    dest: /etc/default/mtproxy
    owner: root
    group: proxy
    mode: 0640
  notify: restart mtproxy service
  tags: mtproxy_service

- name: setup mtproxy service unit
  template:
    src: mtproxy.service
    dest: /etc/systemd/system/mtproxy.service
    mode: 0644
  notify: restart mtproxy service
  tags: mtproxy_service

- name: start mtproxy system service
  systemd:
    name: mtproxy
    state: started
    enabled: yes
    daemon_reload: yes
  tags: mtproxy_service


- name: open mtproxy port, if allowed
  ufw:
    rule: "{{ mtproxy_direct |ternary('allow','deny') }}"
    port: "{{ mtproxy_port |string }}"
  no_log: true
  tags: mtproxy_firewall
...
