---
- name: remove stale docker container
  include_tasks: rmdocker.yml
  when: mtproxy_rmdocker |bool and lin_use_docker |bool
  tags: lin_mtproxy_rmdocker

- name: create group for proxy processes
  group:
    name: proxy
    gid: 13


- name: detect latest mtg release
  github_release:
    repository: 9seconds/mtg
    release: "{{ mtproxy_release }}"
    template: "{download_url}/mtg-linux-amd64"
    creates: "{{ mtproxy_bin_file }}"
    reinstall: "{{ mtproxy_reinstall |bool }}"
  register: latest_mtg_release
  tags: lin_mtproxy_install

- name: download mtproxy
  get_url:
    url: "{{ latest_mtg_release.url }}"
    dest: "{{ mtproxy_bin_file }}"
    mode: 0755
    force: "{{ mtproxy_reinstall |bool }}"
  when: latest_mtg_release is changed
  tags: lin_mtproxy_install


- name: configure mtproxy service
  template:
    src: mtproxy.defaults
    dest: /etc/default/mtproxy
    owner: root
    group: proxy
    mode: 0640
  notify: restart mtproxy service
  tags: lin_mtproxy_service

- name: setup mtproxy service unit
  template:
    src: mtproxy.service
    dest: /etc/systemd/system/mtproxy.service
    mode: 0644
  notify: restart mtproxy service
  tags: lin_mtproxy_service

- name: start mtproxy system service
  systemd:
    name: mtproxy
    state: started
    enabled: yes
    daemon_reload: yes
  tags: lin_mtproxy_service


- name: open mtproxy port, if allowed
  ufw:
    rule: "{{ mtproxy_direct |ternary('allow','deny') }}"
    port: "{{ mtproxy_port |string }}"
  no_log: true
  when: lin_use_firewall |bool
  tags: lin_mtproxy_firewall
...
